# Generated by Django 2.1.7 on 2019-04-10 15:05

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='image/'),
        ),
    ]
