# Generated by Django 2.1.7 on 2019-04-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pickup_check',
            field=models.BooleanField(default=False),
        ),
    ]
