# Generated by Django 2.1.7 on 2019-05-12 20:56

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_pickup_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('host', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', '新着'), ('recruiting', '募集中'), ('over', '締切'), ('finished', '終了')], default='finished', max_length=10)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='image/')),
            ],
        ),
    ]
