# Generated by Django 2.1.7 on 2019-05-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='status',
            field=models.CharField(choices=[('新着', '新着'), ('募集中', '募集中'), ('締切', '締切'), ('終了', '終了')], default='終了', max_length=10),
        ),
    ]
